---
title: "Explaining the CFO Act of 1990"
description: "Some pretense on the Department of Defense never passing an audit."
author: "Nathan States"
date: "02/18/2023"
draft: true
---

There's a good chance that if you've heard of this Act before reading this post, you read it in relation to the Department of Defense being unable to "pass" an audit. I want to give a more detailed breakdown about the Pentagon's financial struggles, but in order to do that, I need to describe this Act in detail. 

## CFO Act of 1990 

The Government Accountability Office (GAO) has a really good [report](https://www.gao.gov/products/gao-20-566) that I recommend reading if you want a comprehensive. The only problem is that it's 140 pages long, so here's a paraphrased version of it. 

Financial management in government has changed dramatically since the end of WW2, though this Act is considered the most important by the GAO. Prior to 1990, government auditors *did* exist, and they routinely found waste, fraud, or other financial misconduct. The report notes some of the major incidents. 

> [...] In 1988, we reported on numerous internal control problems across agencies, such as the Department of Defense (DOD) being unable to account for hundreds of millions of dollars in advances that foreign customers paid for equipment, over $50 million in undetected fraudulent insurance claims paid by the Federal Crop Insurance Corporation, millions of dollars in interest penalties because agencies paid 25 percent of their bills late, and over $350 million in lost interest because agencies paid their bills too soon.
> 
> **Pg. 3**

During the 1980s, there was significant media buzz surrounding the DoD's spending habits, led by a news story discussing the purchase of a \$600 hammer. As [gov.exec](https://www.govexec.com/federal-news/1998/12/the-myth-of-the-600-hammer/5271/) explains, they didn't actually spend \$600 - the DoD's financial management is so shit that it was actually an error duplicated across multiple accounting ledgers - but the story would generate substantial buzz. A report by Chuck Spinney titled "Defense Facts and Life" would offer more proof (here's an [interesting story](https://www.grassley.senate.gov/news/commentary/grassley-spinney-op-ed-don-t-let-pentagon-dip-its-bag-old-tricks) on the incident) of government waste, which, combined with the Savings and Loan crisis of the 1980s, would eventually lead to the passing of the CFO Act of 1990. 

Even though this Act is usually brought up in the context of audits, it doesn't require departments submit them annually. What this Act did was provide a framework for financial management by increasing the authority of the OMB to direct financial management within government. Two new positions were created by this Act; the Deputy Director of Management, essentially the CFO of the government, and the Office of Federal Financial Management, who carry out government-wide initiatives. In addition, each of the 24 major departments were assigned their own CFO, and all 24 CFOs meet up to put forth 5 year progression plans. 

A whole bunch of Acts associated with these plans were passed as a result; the report has a good figure showing some of them.  

-screenshot-

The most important Acts are the GMRA Act of 1994, which requires annual audits from each of the 24 departments, and the FFMIA Act of 1996, which standardized certain financial management systems. The GAO tracked the latter of those in term of department compliance in the report.  

-screenshot-



## Results 

-table-

## Why Care? 

I hope some people got a chuckle reading the footnotes on the table. Arthur Andersen was the firm responsible for "auditing" *Enron*, once the sixth largest corporation in the United States. They quickly collapsed once it was discovered their profits were largely the result of accounting fraud; Arthur Andersen would later be indicted by the DOJ for their (alleged) complicity. Given their conduct in that case, it really shouldn't be a surprise their work in other areas was similarly lacking.  

This does raise some questions. Why did NASA struggle so much while other agencies didn't? Departments like HHS have budgets ten times over that of NASA, even if we were to account for discretionary vs. mandatory budgeting, yet those departments have received unmodified opinions for decades. For that matter, why do several other departments, like DOS and HUD, go years passing audits, only to find themselves failing multiple in a row? 

If the answer is the same reason why Arthur Andersen failed to properly inspect Enron, then the question of auditor independence should be discussed. The same auditors who are providing services to some of the largest government contractors are *also* the same ones auditing those government departments in order to improve their financial security. There is a clear conflict of interest that exists in this arrangement. 

However, isn't it conspiratorial to think audit firms are appeasing their clients by purposefully ensuring the financial systems of their buyers are sub-par? Ignoring intent, results collected by the PCAOB (source: [me](051f11)) show that audits of publicly traded companies are regularly conducted improperly, with an average deficiency rate of **over 25%** among the eight largest firms. The PCAOB doesn't review the audits of government departments; that's actually the responsibility of the GAO, though it's far from their primary focus. The audit reviews they've done, especially in regards to the DoD, [have not been glowing](https://www.gao.gov/products/gao-10-163t). 

Over the past two decades, government contracting has increased enormously. There is absolutely no question that government waste, especially in the DoD, [exists](https://www.npr.org/2011/08/31/140092937/panel-finds-widespread-waste-in-wartime-contracts). It exists outside of it, but the area that should be receiving the most attention is getting the least. Anyone who is genuinely concerned with government waste and isn't starting with the DoD and/or government contracting is missing the big picture. 

## Some Other Stuff  

Receiving unmodified opinions doesn't mean a company's financials are entirely in order. 

-chart- 

Auditors will classify problems into different categories, including ___, material weaknesses, and significant deficiencies. The chart only shows material weaknesses, which indicate a deficiency/combination of deficiencies that *could* potentially cause a financial misstatement. Audit opinions only represent the *opinion* that the financial statements are presented fairly, not whether there's a possibility they aren't. 

When it comes to the DoD, they keep finding problems faster than they can fix them. FY 2022 was the sixth straight year the department reported the same or more material weaknesses. In some ways, it's a good thing. Acknowledging problems is the step to fixing them, but how long will it take to actually start fixing them remains to be seen. 
